### ISSUE TITLE
Any plan to release all variants?

### ISSUE THREAD

**Issue by egg-west** [baitingzbt/PEDA#1]
Dear authors,

Thank you for releasing the codes as well as the dataset. I find them convenient to use and the code runs well. 

I'm wondering whether there is a plan to release a complete set of the data.

Kind regards,
Ethan

**Comment by baitingzbt** [comment]
Hi Ethan,

Thanks for asking and interest in our project. Due to storage limit, it will take some time to release all variants. But we can maybe release the data generation codes in the next days so you can re-generate any variant yourself. We will get back to you once this is done.

The released dataset include everything we used for experiments in the paper, including the Appendix.

Sincerely,
Baiting Zhu

**Comment by baitingzbt** [comment]
Hi Ethan,

Data collection code has been updated. I am going ahead to close this issue, feel free to re-open it for other related questions.

Thanks,
Baiting Zhu
